# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base_msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='base_msg.proto',
  package='drawml',
  serialized_pb=_b('\n\x0e\x62\x61se_msg.proto\x12\x06\x64rawml\"+\n\x0b\x42\x61seMessage\x12\x0e\n\x06header\x18\x01 \x02(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BASEMESSAGE = _descriptor.Descriptor(
  name='BaseMessage',
  full_name='drawml.BaseMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='drawml.BaseMessage.header', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='drawml.BaseMessage.body', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=69,
)

DESCRIPTOR.message_types_by_name['BaseMessage'] = _BASEMESSAGE

BaseMessage = _reflection.GeneratedProtocolMessageType('BaseMessage', (_message.Message,), dict(
  DESCRIPTOR = _BASEMESSAGE,
  __module__ = 'base_msg_pb2'
  # @@protoc_insertion_point(class_scope:drawml.BaseMessage)
  ))
_sym_db.RegisterMessage(BaseMessage)


# @@protoc_insertion_point(module_scope)
