# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_master.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='client_master.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x13\x63lient_master.proto\"\xc9\x03\n\x13TaskRegisterRequest\x12K\n\x17result_receiver_address\x18\x01 \x01(\x0b\x32*.TaskRegisterRequest.ResultReceiverAddress\x12\x34\n\nsleep_task\x18\n \x01(\x0b\x32\x1e.TaskRegisterRequest.SleepTaskH\x00\x12O\n\x18tensorflow_learning_task\x18\x0b \x01(\x0b\x32+.TaskRegisterRequest.TensorflowLearningTaskH\x00\x12G\n\x14tensorflow_test_task\x18\x0c \x01(\x0b\x32\'.TaskRegisterRequest.TensorflowTestTaskH\x00\x1a?\n\x15ResultReceiverAddress\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x1a\x1c\n\tSleepTask\x12\x0f\n\x07seconds\x18\x01 \x01(\x05\x1a\x18\n\x16TensorflowLearningTask\x1a\x14\n\x12TensorflowTestTaskB\x06\n\x04task\"N\n\x14TaskRegisterResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nerror_code\x18\x02 \x01(\t\x12\x12\n\ntask_token\x18\x03 \x01(\x0c\"\x11\n\x0fTaskRegisterACK\"\'\n\x11TaskCancelRequest\x12\x12\n\ntask_token\x18\x01 \x01(\x0c\"L\n\x12TaskCancelResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x12\n\nerror_code\x18\x02 \x01(\t\x12\x12\n\ntask_token\x18\x03 \x01(\x0c\"\x86\x02\n\x07Message\x12\x31\n\x11task_register_req\x18\x01 \x01(\x0b\x32\x14.TaskRegisterRequestH\x00\x12\x32\n\x11task_register_res\x18\x02 \x01(\x0b\x32\x15.TaskRegisterResponseH\x00\x12-\n\x11task_register_ack\x18\x03 \x01(\x0b\x32\x10.TaskRegisterACKH\x00\x12-\n\x0ftask_cancel_req\x18\x04 \x01(\x0b\x32\x12.TaskCancelRequestH\x00\x12.\n\x0ftask_cancel_res\x18\x05 \x01(\x0b\x32\x13.TaskCancelResponseH\x00\x42\x06\n\x04\x62odyb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TASKREGISTERREQUEST_RESULTRECEIVERADDRESS = _descriptor.Descriptor(
  name='ResultReceiverAddress',
  full_name='TaskRegisterRequest.ResultReceiverAddress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='TaskRegisterRequest.ResultReceiverAddress.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ip', full_name='TaskRegisterRequest.ResultReceiverAddress.ip', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='TaskRegisterRequest.ResultReceiverAddress.port', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=332,
  serialized_end=395,
)

_TASKREGISTERREQUEST_SLEEPTASK = _descriptor.Descriptor(
  name='SleepTask',
  full_name='TaskRegisterRequest.SleepTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds', full_name='TaskRegisterRequest.SleepTask.seconds', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=425,
)

_TASKREGISTERREQUEST_TENSORFLOWLEARNINGTASK = _descriptor.Descriptor(
  name='TensorflowLearningTask',
  full_name='TaskRegisterRequest.TensorflowLearningTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=427,
  serialized_end=451,
)

_TASKREGISTERREQUEST_TENSORFLOWTESTTASK = _descriptor.Descriptor(
  name='TensorflowTestTask',
  full_name='TaskRegisterRequest.TensorflowTestTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=453,
  serialized_end=473,
)

_TASKREGISTERREQUEST = _descriptor.Descriptor(
  name='TaskRegisterRequest',
  full_name='TaskRegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result_receiver_address', full_name='TaskRegisterRequest.result_receiver_address', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sleep_task', full_name='TaskRegisterRequest.sleep_task', index=1,
      number=10, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tensorflow_learning_task', full_name='TaskRegisterRequest.tensorflow_learning_task', index=2,
      number=11, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tensorflow_test_task', full_name='TaskRegisterRequest.tensorflow_test_task', index=3,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_TASKREGISTERREQUEST_RESULTRECEIVERADDRESS, _TASKREGISTERREQUEST_SLEEPTASK, _TASKREGISTERREQUEST_TENSORFLOWLEARNINGTASK, _TASKREGISTERREQUEST_TENSORFLOWTESTTASK, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='task', full_name='TaskRegisterRequest.task',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=24,
  serialized_end=481,
)


_TASKREGISTERRESPONSE = _descriptor.Descriptor(
  name='TaskRegisterResponse',
  full_name='TaskRegisterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='TaskRegisterResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='TaskRegisterResponse.error_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_token', full_name='TaskRegisterResponse.task_token', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=483,
  serialized_end=561,
)


_TASKREGISTERACK = _descriptor.Descriptor(
  name='TaskRegisterACK',
  full_name='TaskRegisterACK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=563,
  serialized_end=580,
)


_TASKCANCELREQUEST = _descriptor.Descriptor(
  name='TaskCancelRequest',
  full_name='TaskCancelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_token', full_name='TaskCancelRequest.task_token', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=582,
  serialized_end=621,
)


_TASKCANCELRESPONSE = _descriptor.Descriptor(
  name='TaskCancelResponse',
  full_name='TaskCancelResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='TaskCancelResponse.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error_code', full_name='TaskCancelResponse.error_code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_token', full_name='TaskCancelResponse.task_token', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=623,
  serialized_end=699,
)


_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_register_req', full_name='Message.task_register_req', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_register_res', full_name='Message.task_register_res', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_register_ack', full_name='Message.task_register_ack', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_cancel_req', full_name='Message.task_cancel_req', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_cancel_res', full_name='Message.task_cancel_res', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='body', full_name='Message.body',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=702,
  serialized_end=964,
)

_TASKREGISTERREQUEST_RESULTRECEIVERADDRESS.containing_type = _TASKREGISTERREQUEST
_TASKREGISTERREQUEST_SLEEPTASK.containing_type = _TASKREGISTERREQUEST
_TASKREGISTERREQUEST_TENSORFLOWLEARNINGTASK.containing_type = _TASKREGISTERREQUEST
_TASKREGISTERREQUEST_TENSORFLOWTESTTASK.containing_type = _TASKREGISTERREQUEST
_TASKREGISTERREQUEST.fields_by_name['result_receiver_address'].message_type = _TASKREGISTERREQUEST_RESULTRECEIVERADDRESS
_TASKREGISTERREQUEST.fields_by_name['sleep_task'].message_type = _TASKREGISTERREQUEST_SLEEPTASK
_TASKREGISTERREQUEST.fields_by_name['tensorflow_learning_task'].message_type = _TASKREGISTERREQUEST_TENSORFLOWLEARNINGTASK
_TASKREGISTERREQUEST.fields_by_name['tensorflow_test_task'].message_type = _TASKREGISTERREQUEST_TENSORFLOWTESTTASK
_TASKREGISTERREQUEST.oneofs_by_name['task'].fields.append(
  _TASKREGISTERREQUEST.fields_by_name['sleep_task'])
_TASKREGISTERREQUEST.fields_by_name['sleep_task'].containing_oneof = _TASKREGISTERREQUEST.oneofs_by_name['task']
_TASKREGISTERREQUEST.oneofs_by_name['task'].fields.append(
  _TASKREGISTERREQUEST.fields_by_name['tensorflow_learning_task'])
_TASKREGISTERREQUEST.fields_by_name['tensorflow_learning_task'].containing_oneof = _TASKREGISTERREQUEST.oneofs_by_name['task']
_TASKREGISTERREQUEST.oneofs_by_name['task'].fields.append(
  _TASKREGISTERREQUEST.fields_by_name['tensorflow_test_task'])
_TASKREGISTERREQUEST.fields_by_name['tensorflow_test_task'].containing_oneof = _TASKREGISTERREQUEST.oneofs_by_name['task']
_MESSAGE.fields_by_name['task_register_req'].message_type = _TASKREGISTERREQUEST
_MESSAGE.fields_by_name['task_register_res'].message_type = _TASKREGISTERRESPONSE
_MESSAGE.fields_by_name['task_register_ack'].message_type = _TASKREGISTERACK
_MESSAGE.fields_by_name['task_cancel_req'].message_type = _TASKCANCELREQUEST
_MESSAGE.fields_by_name['task_cancel_res'].message_type = _TASKCANCELRESPONSE
_MESSAGE.oneofs_by_name['body'].fields.append(
  _MESSAGE.fields_by_name['task_register_req'])
_MESSAGE.fields_by_name['task_register_req'].containing_oneof = _MESSAGE.oneofs_by_name['body']
_MESSAGE.oneofs_by_name['body'].fields.append(
  _MESSAGE.fields_by_name['task_register_res'])
_MESSAGE.fields_by_name['task_register_res'].containing_oneof = _MESSAGE.oneofs_by_name['body']
_MESSAGE.oneofs_by_name['body'].fields.append(
  _MESSAGE.fields_by_name['task_register_ack'])
_MESSAGE.fields_by_name['task_register_ack'].containing_oneof = _MESSAGE.oneofs_by_name['body']
_MESSAGE.oneofs_by_name['body'].fields.append(
  _MESSAGE.fields_by_name['task_cancel_req'])
_MESSAGE.fields_by_name['task_cancel_req'].containing_oneof = _MESSAGE.oneofs_by_name['body']
_MESSAGE.oneofs_by_name['body'].fields.append(
  _MESSAGE.fields_by_name['task_cancel_res'])
_MESSAGE.fields_by_name['task_cancel_res'].containing_oneof = _MESSAGE.oneofs_by_name['body']
DESCRIPTOR.message_types_by_name['TaskRegisterRequest'] = _TASKREGISTERREQUEST
DESCRIPTOR.message_types_by_name['TaskRegisterResponse'] = _TASKREGISTERRESPONSE
DESCRIPTOR.message_types_by_name['TaskRegisterACK'] = _TASKREGISTERACK
DESCRIPTOR.message_types_by_name['TaskCancelRequest'] = _TASKCANCELREQUEST
DESCRIPTOR.message_types_by_name['TaskCancelResponse'] = _TASKCANCELRESPONSE
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE

TaskRegisterRequest = _reflection.GeneratedProtocolMessageType('TaskRegisterRequest', (_message.Message,), dict(

  ResultReceiverAddress = _reflection.GeneratedProtocolMessageType('ResultReceiverAddress', (_message.Message,), dict(
    DESCRIPTOR = _TASKREGISTERREQUEST_RESULTRECEIVERADDRESS,
    __module__ = 'client_master_pb2'
    # @@protoc_insertion_point(class_scope:TaskRegisterRequest.ResultReceiverAddress)
    ))
  ,

  SleepTask = _reflection.GeneratedProtocolMessageType('SleepTask', (_message.Message,), dict(
    DESCRIPTOR = _TASKREGISTERREQUEST_SLEEPTASK,
    __module__ = 'client_master_pb2'
    # @@protoc_insertion_point(class_scope:TaskRegisterRequest.SleepTask)
    ))
  ,

  TensorflowLearningTask = _reflection.GeneratedProtocolMessageType('TensorflowLearningTask', (_message.Message,), dict(
    DESCRIPTOR = _TASKREGISTERREQUEST_TENSORFLOWLEARNINGTASK,
    __module__ = 'client_master_pb2'
    # @@protoc_insertion_point(class_scope:TaskRegisterRequest.TensorflowLearningTask)
    ))
  ,

  TensorflowTestTask = _reflection.GeneratedProtocolMessageType('TensorflowTestTask', (_message.Message,), dict(
    DESCRIPTOR = _TASKREGISTERREQUEST_TENSORFLOWTESTTASK,
    __module__ = 'client_master_pb2'
    # @@protoc_insertion_point(class_scope:TaskRegisterRequest.TensorflowTestTask)
    ))
  ,
  DESCRIPTOR = _TASKREGISTERREQUEST,
  __module__ = 'client_master_pb2'
  # @@protoc_insertion_point(class_scope:TaskRegisterRequest)
  ))
_sym_db.RegisterMessage(TaskRegisterRequest)
_sym_db.RegisterMessage(TaskRegisterRequest.ResultReceiverAddress)
_sym_db.RegisterMessage(TaskRegisterRequest.SleepTask)
_sym_db.RegisterMessage(TaskRegisterRequest.TensorflowLearningTask)
_sym_db.RegisterMessage(TaskRegisterRequest.TensorflowTestTask)

TaskRegisterResponse = _reflection.GeneratedProtocolMessageType('TaskRegisterResponse', (_message.Message,), dict(
  DESCRIPTOR = _TASKREGISTERRESPONSE,
  __module__ = 'client_master_pb2'
  # @@protoc_insertion_point(class_scope:TaskRegisterResponse)
  ))
_sym_db.RegisterMessage(TaskRegisterResponse)

TaskRegisterACK = _reflection.GeneratedProtocolMessageType('TaskRegisterACK', (_message.Message,), dict(
  DESCRIPTOR = _TASKREGISTERACK,
  __module__ = 'client_master_pb2'
  # @@protoc_insertion_point(class_scope:TaskRegisterACK)
  ))
_sym_db.RegisterMessage(TaskRegisterACK)

TaskCancelRequest = _reflection.GeneratedProtocolMessageType('TaskCancelRequest', (_message.Message,), dict(
  DESCRIPTOR = _TASKCANCELREQUEST,
  __module__ = 'client_master_pb2'
  # @@protoc_insertion_point(class_scope:TaskCancelRequest)
  ))
_sym_db.RegisterMessage(TaskCancelRequest)

TaskCancelResponse = _reflection.GeneratedProtocolMessageType('TaskCancelResponse', (_message.Message,), dict(
  DESCRIPTOR = _TASKCANCELRESPONSE,
  __module__ = 'client_master_pb2'
  # @@protoc_insertion_point(class_scope:TaskCancelResponse)
  ))
_sym_db.RegisterMessage(TaskCancelResponse)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGE,
  __module__ = 'client_master_pb2'
  # @@protoc_insertion_point(class_scope:Message)
  ))
_sym_db.RegisterMessage(Message)


# @@protoc_insertion_point(module_scope)
